environment:
  nodejs_version: "9"
  # TEST_SERIES: "1"
  matrix:
    - TEST_TYPE: base
    - TEST_TYPE: single
    - TEST_TYPE: plugin
    - TEST_TYPE: multi
    - TEST_TYPE: command
    - TEST_TYPE: hook
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version x64
  - git config --global user.email "oclif@example.com"
  - git config --global user.name "oclif"
  - yarn
test_script:
  - .\node_modules\.bin\nps lint
  - .\node_modules\.bin\nps test.%TEST_TYPE%
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

build: off

