---
version: 2.1

orbs:
  release-management: salesforce/npm-release-management@4

jobs:
  lint: &lint
    docker:
      - image: node:latest
    # environment:
    #   - TEST_SERIES: 1
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v5-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v5-{{checksum ".circleci/config.yml"}}
            - v5
      - run: yarn add -D mocha-junit-reporter@1
      - run: yarn exec nps lint
      - persist_to_workspace: {root: node_modules,  paths: ["*"]}
  compile-typescript:
    <<: *lint
    steps:
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: yarn
      - run: rm -rf lib && npx tsc --noEmit && rm -fr lib
  test:
    <<: *lint
    parameters:
      test:
        type: string
      image: 
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test.<< parameters.test >>
      - store_test_results:
          path: ~/cli/reports
  node-12-devcli: &node-12-devcli
    docker:
      - image: oclif/nsis:12.0.0-16
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v6-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v6-yarn-{{checksum ".circleci/config.yml"}}
      - run: 'echo "Node: `node --version`"'
      - run: yarn
      - run: .circleci/loadgpg
      - run: yarn add -D nyc@13 @oclif/nyc-config@1
      - run: ./node_modules/.bin/tsc
      - run: ./bin/run --version
      - run: ./bin/run --help

  cache:
    <<: *lint
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
      - run: yarn add -D mocha-junit-reporter@1
      - run: yarn exec nps test.command
      - save_cache:
          key: v5-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
workflows:
  version: 2
  oclif:
    jobs:
      - lint
      - compile-typescript
      - node-12-devcli
      - test:
          matrix:
            parameters:
              image: [node:latest, node:14, node:12]
              test: [multi, base, plugin, single, command, hook]
          name: << matrix.image >>-<< matrix.test >>
          requires: [lint, compile-typescript]
      - cache: {requires: [release-management/release-package] }
      - release-management/release-package:
          context: org-global
          github-release: true
          prerelease: true
          tag: v2
          requires:
            - lint
            - compile-typescript
            - test
          filters:
            branches:
              only: main
  nightly:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - lint
      - compile-typescript
      - node-12-devcli
      - test:
          matrix:
            parameters:
              image: [node:latest, node:14, node:12]
              test: [multi, base, plugin, single, command, hook]
          name: << matrix.image >>-<< matrix.test >>
          requires: [lint, compile-typescript]
