---
version: 2
jobs:
  node-latest-base: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-
            - v0-yarn-{{checksum ".circleci/config.yml"}}-master-
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps test.base
      - store_test_results: &store_test_results
          path: ~/cli/reports
      - save_cache:
          key: v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  node-latest-single:
    <<: *test
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps test.single
      - store_test_results: *store_test_results
  node-latest-plugin:
    <<: *test
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps test.plugin
      - store_test_results: *store_test_results
  node-latest-multi:
    <<: *test
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps test.multi
      - store_test_results: *store_test_results
  node-8-base:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps test.base
      - store_test_results: *store_test_results
  node-8-single:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps test.single
      - store_test_results: *store_test_results
  node-8-plugin:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps test.plugin
      - store_test_results: *store_test_results
  node-8-multi:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps test.multi
      - store_test_results: *store_test_results

  lint:
    <<: *test
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: yarn exec nps lint
      - store_test_results: *store_test_results

  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/yarn
      - run: .circleci/setup_git
      - run: ./node_modules/.bin/nps release

workflows:
  version: 2
  create-dxcli:
    jobs:
      - lint
      - node-latest-base
      - node-latest-single
      - node-latest-plugin
      - node-latest-multi
      # - node-8-base
      # - node-8-single
      # - node-8-plugin
      # - node-8-multi
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - lint
            - node-latest-base
            - node-latest-single
            - node-latest-plugin
            - node-latest-multi
            # - node-8-base
            # - node-8-single
            # - node-8-plugin
            # - node-8-multi
