name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        node_version: [lts/*, latest]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn nps lint
      - run: yarn build
      - run: yarn test:unit
  publish:
    needs: [unit-tests]
    strategy:
      matrix:
        node_version: [lts/*, latest]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn build
      - run: yarn mocha test/integration/publish.test.ts --timeout 900000
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PRESERVE_ARTIFACTS:  ${{ vars.PRESERVE_ARTIFACTS }}

  win-build:
    needs: [unit-tests]
    strategy:
      matrix:
        node_version: [lts/*, latest]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn build
      - run: |
          sudo apt-get update
          sudo apt-get install osslsigncode nsis
      - run: yarn mocha test/integration/win.test.ts --timeout 600000
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PRESERVE_ARTIFACTS:  ${{ vars.PRESERVE_ARTIFACTS }}
  mac-build:
    needs: [unit-tests]
    strategy:
      matrix:
        node_version: [lts/*, latest]
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn build
      - run: yarn mocha test/integration/macos.test.ts --timeout 600000
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PRESERVE_ARTIFACTS:  ${{ vars.PRESERVE_ARTIFACTS }}

  deb-build:
    needs: [unit-tests]
    env:
      OCLIF_DEB_PRIVATE_KEY: ${{ secrets.OCLIF_DEB_PRIVATE_KEY }}
    strategy:
      matrix:
        node_version: [lts/*, latest]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn build
      - run: echo -n "$OCLIF_DEB_PRIVATE_KEY" | gpg --import

      - run: yarn mocha test/integration/deb.test.ts --timeout 600000
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OCLIF_DEB_KEY: ${{ secrets.OCLIF_DEB_KEY }}
          PRESERVE_ARTIFACTS:  ${{ vars.PRESERVE_ARTIFACTS }}

